# development environment
name: tqdm
channels:
- conda-forge
- defaults
dependencies:
# base
- python >=3.7
- pip
- ipykernel
- ipywidgets
- setuptools
- setuptools_scm
- toml
# test env managers
- pre-commit
- tox
- asv
# tests (native)
- pytest
- pytest-cov
- pytest-timeout
- pytest-asyncio
- nbval
- coverage
# extras
- dask               # dask
- matplotlib         # gui
- numpy              # pandas, keras, contrib.tenumerate
- pandas
- pyarrow            # pandas
- tensorflow         # keras
- slack-sdk          # contrib.slack
- requests           # contrib.telegram
- rich               # rich
- argopt             # `cd wiki && pymake`
- twine              # `pymake check pypi`
- build              # `python -m build`
# `cd docs && pymake`
- mkdocs-material
- pygments
- pymdown-extensions
- pip:
  - py-make >=0.1.0                                          # `make/pymake`
  - mkdocs-minify-plugin                                     # `cd docs && pymake`
  - git+https://github.com/tqdm/jsmin@fix-pip#egg=jsmin      # `cd docs && pymake`
  - pydoc-markdown >=4.6                                     # `cd docs && pymake`
