name: Post Release
on:
  release:
    types: [published]
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
    - name: Update Releases
      run: |
        make
        git config user.email "$GIT_AUTHOR_EMAIL"
        git config user.name "$GIT_AUTHOR_NAME"
        git commit -a -m "update release notes to ${GITHUB_REF#refs/tags/}"
        git push
      env:
        GIT_AUTHOR_NAME: ${{ github.event.sender.login }}
        GIT_AUTHOR_EMAIL: ${{ github.event.sender.login }}@users.noreply.github.com
